architect:
  - amihaiemil
  - andronachev
install: |
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
merge:
  script: |-
    bundle install
    bundle exec rake
release:
  script: |-
    echo 'Nothing to release yet'
    exit -1
deploy:
  script: |-
    echo 'Nothing to deploy yet'
    exit -1
