architect:
  - amihaiemil
  - andronachev
install: |
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
  bundle install
merge:
  script: |-
    bundle exec rake
deploy:
  script: |-
    echo 'Nothing to deploy yet'
    exit -1
decrypt:
  rubygems.yml: "repo/rcfg/rubygems.yml.asc"
release:
  script: |-
    chmod +x ./release.sh
    ./release.sh
