architect:
  - amihaiemil
  - andronachev
install: |
  bundle install
merge:
  script: |-
    bundle exec rake
release:
  script: |-
    echo 'Nothing to release yet'
    exit -1
deploy:
  script: |-
    echo 'Nothing to deploy yet'
    exit -1
