---
language: ruby
cache: bundler
rvm:
  - 2.7.0
before_install: gem install bundler -v 2.1.4
branches:
  only:
    - master
script:
  - bundle install
  - bundler exec rake
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
